-- ==== INSERCIÓN RAW DATA ====

-- INSERT RAW_CLIENTES
CALL UTILS.SP_LOAD_EXCEL_TO_RAW_VARCHAR(BUILD_SCOPED_FILE_URL('@staging.s3_staging', 'clientes/clientes.xlsx'), 'DMS_ASSESSMENT.BRONZE.RAW_CLIENTES'); 

-- HARDCODE FILE_NAME (OPTIONAL)
UPDATE BRONZE.RAW_CLIENTES SET FILE_NAME = 'raw/clientes/clientes.xlsx';

-- INSERT RAW_CUOTAS
COPY INTO BRONZE.RAW_CUOTAS (ID_VENDEDOR, PERIODO, CUOTA_MENSUAL, REGION_CO, FILE_NAME)
FROM (
    SELECT 
    $1:id_vendedor::VARCHAR,
    $1:periodo::VARCHAR,
    $1:cuota_mensual::VARCHAR,
    $1:region::VARCHAR,
    METADATA$FILENAME,
  FROM @staging.s3_staging/cuotas/
)
FILE_FORMAT = (FORMAT_NAME = 'utils.ff_json_format')
ON_ERROR = 'CONTINUE';

-- INSERT RAW_PRODUCTOS
CALL UTILS.SP_LOAD_EXCEL_TO_RAW_VARCHAR(BUILD_SCOPED_FILE_URL('@staging.s3_staging', 'productos/productos.xlsx'), 'DMS_ASSESSMENT.BRONZE.RAW_PRODUCTOS');

-- HARDCODE FILE_NAME (OPTIONAL)
UPDATE BRONZE.RAW_PRODUCTOS SET FILE_NAME = 'raw/productos/productos.xlsx';

-- INSERT RAW_VENDEDORES
COPY INTO BRONZE.RAW_VENDEDORES (ID_VENDEDOR, NOMBRE_VENDEDOR, REGION_CO, FECHA_INGRESO, 
    TIPO_DE_CONTRATO, FILE_NAME)
FROM (
  SELECT $1, $2, $3, $4, $5, METADATA$FILENAME
  FROM @staging.s3_staging/vendedores/
)
FILE_FORMAT = (FORMAT_NAME = 'utils.ff_txt_format')
ON_ERROR = 'CONTINUE';

-- INSERT RAW_VENTAS
COPY INTO BRONZE.RAW_VENTAS (ID_VENTA, FECHA_VENTA, ID_PRODUCTO, ID_CLIENTE, ID_VENDEDOR, CANTIDAD, PRECIO_UNITARIO, TOTAL_VENTA, FILE_NAME)
FROM (
  SELECT $1, $2, $3, $4, $5, $6, $7, $8, METADATA$FILENAME
  FROM @staging.s3_staging/ventas/
)
FILE_FORMAT = (FORMAT_NAME = 'utils.ff_csv_format')
ON_ERROR = 'CONTINUE';
