-- ==== CREACIÓN DE TABLAS ====

-- CREACIÓN DE TABLA CLIENTES
CREATE TABLE IF NOT EXISTS BRONZE.RAW_CLIENTES (
    ID_CLIENTE      VARCHAR,
    NOMBRE_CLIENTE  VARCHAR,
    TIPO_CLIENTE    VARCHAR,
    CIUDAD          VARCHAR,
    DIRECCION       VARCHAR,
    FECHA_REGISTRO  VARCHAR,
    -- AUDITORIA
    FILE_NAME       VARCHAR,
    LOAD_TIMESTAMP  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- CREACIÓN DE TABLA CUOTA
CREATE TABLE IF NOT EXISTS BRONZE.RAW_CUOTAS (
    ID_VENDEDOR     VARCHAR,
    PERIODO         VARCHAR,
    CUOTA_MENSUAL   VARCHAR, 
    REGION_CO       VARCHAR,  -- SNOWFLAKE KEYWORD SUF _CO
    -- AUDITORIA
    FILE_NAME       VARCHAR,
    LOAD_TIMESTAMP  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- CREACIÓN DE TABLA PRODUCTOS
CREATE TABLE IF NOT EXISTS BRONZE.RAW_PRODUCTOS (
    ID_PRODUCTO     VARCHAR,
    NOMBRE_PRODUCTO VARCHAR,
    CATEGORIA       VARCHAR,
    PRECIO_UNITARIO VARCHAR,
    LABORATORIO     VARCHAR,
    -- AUDITORIA
    FILE_NAME       VARCHAR,
    LOAD_TIMESTAMP  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
); 

-- CREACIÓN DE TABLA VENDEDORES
CREATE TABLE IF NOT EXISTS BRONZE.RAW_VENDEDORES (
    ID_VENDEDOR      VARCHAR,
    NOMBRE_VENDEDOR  VARCHAR,
    REGION_CO        VARCHAR, -- SNOWFLAKE KEYWORD SUF _CO
    FECHA_INGRESO    VARCHAR,
    TIPO_DE_CONTRATO VARCHAR,
    -- AUDITORIA
    FILE_NAME       VARCHAR,
    LOAD_TIMESTAMP  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- CREACIÓN DE TABLA VENTAS
CREATE TABLE IF NOT EXISTS BRONZE.RAW_VENTAS(
    ID_VENTA        VARCHAR,
    FECHA_VENTA     VARCHAR,
    ID_PRODUCTO     VARCHAR,
    ID_CLIENTE      VARCHAR,
    ID_VENDEDOR     VARCHAR,
    CANTIDAD        VARCHAR,
    PRECIO_UNITARIO VARCHAR,
    TOTAL_VENTA     VARCHAR,
    -- AUDITORIA
    FILE_NAME       VARCHAR,
    LOAD_TIMESTAMP  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);