-- ==== LIMPIEZA PRE-CARGUE SILVER ====

-- LIMPIEZA DE TABLA RAW
TRUNCATE TABLE BRONZE.RAW_CLIENTES;

-- LIMPIEZA DE TABLA RAW
TRUNCATE TABLE BRONZE.RAW_CUOTAS;

-- LIMPIEZA DE TABLA RAW
TRUNCATE TABLE BRONZE.RAW_PRODUCTOS;

-- LIMPIEZA DE TABLA RAW
TRUNCATE TABLE BRONZE.RAW_VENDEDORES;

-- LIMPIEZA DE TABLA RAW
TRUNCATE TABLE BRONZE.RAW_VENTAS;