-- ==== CREACIÓN DE SCHEMAS ====
CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;
CREATE TRANSIENT SCHEMA IF NOT EXISTS STAGING; -- AHORRO EN COSTOS EVITANDO FAIL-SAFE
CREATE SCHEMA IF NOT EXISTS UTILS; -- UTILIDADES PARA PROCESOS ELT