-- ==== CREAR FILE FORMATS PARA CADA ARCHIVO ====

-- FF PARA CSV
CREATE OR REPLACE FILE FORMAT utils.ff_csv_format
  TYPE = 'CSV' 
  FIELD_DELIMITER = ',' 
  SKIP_HEADER = 1 
  NULL_IF = ('NULL', 'null') 
  EMPTY_FIELD_AS_NULL = TRUE;

-- FF PARA TXT SEPARADOR '|'
CREATE OR REPLACE FILE FORMAT utils.ff_txt_format
  TYPE = 'CSV' 
  FIELD_DELIMITER = '|' 
  SKIP_HEADER = 1;

-- FF PARA JSON
CREATE OR REPLACE FILE FORMAT utils.ff_json_format
  TYPE = 'JSON' 
  STRIP_OUTER_ARRAY = TRUE
  IGNORE_UTF8_ERRORS = TRUE;