-- ==== PROCESO DE TRANFORMACIÓN A LAYER SILVER ====

-- TABLA CLIENTES
CREATE OR REPLACE TABLE SILVER.CLIENTES AS
WITH CTE_RN AS (
    SELECT
         ID_CLIENTE    
        ,NOMBRE_CLIENTE
        ,TIPO_CLIENTE 
        ,NVL(COALESCE(B.ESTANDAR, TRIM(UPPER(A.CIUDAD))), 'DESCONOCIDA') AS CIUDAD        
        ,DIRECCION     
        ,COALESCE(
            TRY_TO_DATE(FECHA_REGISTRO, 'DD-MM-YYYY'),
            TRY_TO_DATE(FECHA_REGISTRO, 'YYYY-MM-DD'),
            TRY_TO_DATE(FECHA_REGISTRO, 'DD/MM/YYYY'),
            TRY_TO_DATE(FECHA_REGISTRO, 'YYYY/MM/DD')
        ) AS FECHA_REGISTRO
        ,CURRENT_TIMESTAMP() AS PROCESSED_AT
        ,ROW_NUMBER() OVER(PARTITION BY ID_CLIENTE, NOMBRE_CLIENTE ORDER BY ID_CLIENTE) AS RN
    FROM BRONZE.RAW_CLIENTES AS A
    LEFT JOIN SILVER.MAPEO_CIUDADES AS B
        ON TRIM(A.CIUDAD) = B.VARIACION
)
SELECT
     ID_CLIENTE
    ,NOMBRE_CLIENTE
    ,TIPO_CLIENTE
    ,INITCAP(CIUDAD) AS CIUDAD
    ,DIRECCION
    ,FECHA_REGISTRO
    ,PROCESSED_AT
FROM CTE_RN
WHERE RN = 1;

-- TABLA CUOTAS
CREATE OR REPLACE SEQUENCE SILVER.SEQ_CUOTA START = 1 INCREMENT = 1; -- CREAR SEQ PARA PK CUOTA

CREATE OR REPLACE TABLE SILVER.CUOTA AS
WITH CTE_RN AS 
(
    SELECT 
         ID_VENDEDOR
        ,TO_DATE(PERIODO || '-01') AS PERIODO
        ,TRY_TO_NUMBER(CUOTA_MENSUAL) AS CUOTA_MENSUAL
        --,TRANSLATE(REGION_CO, 'áéíóúÁÉÍÓÚüÜ', 'aeiouAEIOUuU') AS REGION_CO
        ,ROW_NUMBER() OVER(PARTITION BY ID_VENDEDOR, PERIODO, REGION_CO ORDER BY PERIODO) AS RN
    FROM BRONZE.RAW_CUOTAS
)
SELECT
    'Q' || LPAD(SILVER.SEQ_CUOTA.NEXTVAL, 4, '0') AS ID_CUOTA
    ,ID_VENDEDOR
    ,PERIODO
    ,CUOTA_MENSUAL
    --,REGION_CO AJUSTANDO AL MODELO ERD
    ,CURRENT_TIMESTAMP() AS PROCESSED_AT
FROM CTE_RN
WHERE RN = 1;

-- TABLA PRODUCTOS
CREATE OR REPLACE TABLE SILVER.PRODUCTOS AS
WITH CTE_RN AS (
    SELECT
         ID_PRODUCTO
        ,INITCAP(
            TRANSLATE(
                TRIM(REPLACE(NOMBRE_PRODUCTO, '_', ' ')), 
                'áéíóúÁÉÍÓÚüÜ®',
                'aeiouAEIOUuU'
            )
        ) AS NOMBRE_PRODUCTO
        ,NVL(TRIM(TRANSLATE(CATEGORIA, 'áéíóúÁÉÍÓÚüÜ®', 'aeiouAEIOUuU')), 'Desconocido') AS CATEGORIA
        ,TRY_TO_NUMBER(PRECIO_UNITARIO) AS PRECIO_UNITARIO
        ,TRANSLATE(LABORATORIO, 'áéíóúÁÉÍÓÚüÜ', 'aeiouAEIOUuU') AS LABORATORIO
        ,ROW_NUMBER() OVER(PARTITION BY ID_PRODUCTO ORDER BY ID_PRODUCTO) AS RN
    FROM BRONZE.RAW_PRODUCTOS
)
SELECT
     ID_PRODUCTO
    ,NOMBRE_PRODUCTO
    ,CATEGORIA
    ,PRECIO_UNITARIO
    ,LABORATORIO
    ,CURRENT_TIMESTAMP() AS PROCESSED_AT
FROM CTE_RN
WHERE RN = 1;

-- TABLA VENDEDORES
CREATE OR REPLACE TABLE SILVER.VENDEDORES AS
WITH CTE_RN AS (
    SELECT
         ID_VENDEDOR
        ,TRANSLATE(NOMBRE_VENDEDOR, 'áéíóúÁÉÍÓÚüÜ', 'aeiouAEIOUuU') AS NOMBRE_VENDEDOR
        ,NVL(TRANSLATE(INITCAP(REGION_CO), 'áéíóúÁÉÍÓÚüÜ', 'aeiouAEIOUuU'), 'Desconocido') AS REGION_CO
        ,TRY_TO_DATE(FECHA_INGRESO) AS FECHA_INGRESO
        ,TIPO_DE_CONTRATO
        ,ROW_NUMBER() OVER(PARTITION BY ID_VENDEDOR ORDER BY FECHA_INGRESO) AS RN
    FROM BRONZE.RAW_VENDEDORES
)
SELECT
    ID_VENDEDOR
    ,NOMBRE_VENDEDOR
    ,REGION_CO
    ,FECHA_INGRESO
    ,TIPO_DE_CONTRATO
    ,CURRENT_TIMESTAMP() AS PROCESSED_AT
FROM CTE_RN
WHERE RN = 1;

-- TABLA VENTAS
CREATE OR REPLACE TABLE SILVER.VENTAS AS 
WITH CTE_RN AS (
    SELECT
         ID_VENTA
        ,COALESCE(
            TRY_TO_DATE(FECHA_VENTA, 'DD-MM-YYYY'),
            TRY_TO_DATE(FECHA_VENTA, 'YYYY-MM-DD'),
            TRY_TO_DATE(FECHA_VENTA, 'DD/MM/YYYY'),
            TRY_TO_DATE(FECHA_VENTA, 'YYYY/MM/DD')
        ) AS FECHA_VENTA
        ,ID_PRODUCTO
        ,ID_CLIENTE
        ,ID_VENDEDOR
        ,TRY_TO_NUMBER(CANTIDAD) AS CANTIDAD
        ,TRY_TO_NUMBER(PRECIO_UNITARIO, 18, 2) AS PRECIO_UNITARIO
        ,TRY_TO_NUMBER(TOTAL_VENTA, 18, 2) AS TOTAL_VENTA
        ,ROW_NUMBER() OVER(PARTITION BY ID_VENTA, ID_PRODUCTO, ID_CLIENTE, ID_VENDEDOR ORDER BY ID_VENTA) AS RN
    FROM BRONZE.RAW_VENTAS
)
SELECT
     ID_VENTA
    ,FECHA_VENTA
    ,ID_PRODUCTO
    ,ID_CLIENTE
    ,ID_VENDEDOR
    ,CANTIDAD
    ,PRECIO_UNITARIO
    ,TOTAL_VENTA
    ,CURRENT_TIMESTAMP() AS PROCESSED_AT
FROM CTE_RN
WHERE RN = 1;