-- ==== ASIGNACIÓN DE LLAVES PRIMARIAS 

ALTER TABLE SILVER.CLIENTES ADD PRIMARY KEY (ID_CLIENTE);
ALTER TABLE SILVER.CUOTA ADD PRIMARY KEY (ID_CUOTA);
ALTER TABLE SILVER.PRODUCTOS ADD PRIMARY KEY (ID_PRODUCTO);
ALTER TABLE SILVER.VENDEDORES ADD PRIMARY KEY (ID_VENDEDOR);
ALTER TABLE SILVER.VENTAS ADD PRIMARY KEY (ID_VENTA);