-- ==== CREACIÓN DE GOLD LAYER ====

-- TABLA DIM_TIEMPO
CREATE OR REPLACE TABLE GOLD.DIM_TIEMPO (
      ID_FECHA     INT PRIMARY KEY
     ,FECHA        DATE
     ,DIA          INT
     ,MES          INT
     ,NOMBRE_MES   VARCHAR
     ,TRIMESTRE    INT
     ,ANIO         INT
     ,PERIODO      DATE
);
 
INSERT INTO GOLD.DIM_TIEMPO (ID_FECHA, FECHA, DIA, MES, NOMBRE_MES, TRIMESTRE, ANIO, PERIODO)
SELECT
     ROW_NUMBER() OVER (ORDER BY DATEADD(DAY, SEQ4(), '2020-01-01')) AS ID_FECHA
    ,TO_DATE(DATEADD(DAY, SEQ4(), '2020-01-01'))                     AS FECHA
    ,DAY(DATEADD(DAY, SEQ4(), '2020-01-01'))                         AS DIA
    ,MONTH(DATEADD(DAY, SEQ4(), '2020-01-01'))                       AS MES
    ,MONTHNAME(DATEADD(DAY, SEQ4(), '2020-01-01'))                   AS NOMBRE_MES
    ,QUARTER(DATEADD(DAY, SEQ4(), '2020-01-01'))                     AS TRIMESTRE
    ,YEAR(DATEADD(DAY, SEQ4(), '2020-01-01'))                        AS ANIO
    ,TO_DATE(TO_CHAR(DATEADD(DAY, SEQ4(), '2020-01-01'), 'YYYY-MM')   || '-01') AS PERIODO
FROM TABLE(GENERATOR(ROWCOUNT => 3650));

-- TABLA DIM_CLIENTES
CREATE OR REPLACE TABLE GOLD.DIM_CLIENTES (
    ID_CLIENTE      VARCHAR PRIMARY KEY
    ,NOMBRE_CLIENTE VARCHAR
    ,TIPO_CLIENTE   VARCHAR
    ,CIUDAD         VARCHAR
    ,DIRECCION      VARCHAR 
    ,FECHA_REGISTRO DATE
    
);

INSERT INTO GOLD.DIM_CLIENTES (ID_CLIENTE, NOMBRE_CLIENTE, TIPO_CLIENTE, CIUDAD, DIRECCION, FECHA_REGISTRO)
SELECT
     ID_CLIENTE
    ,NOMBRE_CLIENTE
    ,TIPO_CLIENTE
    ,CIUDAD
    ,DIRECCION
    ,FECHA_REGISTRO
FROM SILVER.CLIENTES;

-- TABLA DIM_PRODUCTOS
CREATE OR REPLACE TABLE GOLD.DIM_PRODUCTOS (
     ID_PRODUCTO      VARCHAR PRIMARY KEY
    ,NOMBRE_PRODUCTO VARCHAR
    ,CATEGORIA       VARCHAR
    ,PRECIO_UNITARIO NUMBER
    ,LABORATORIO     VARCHAR
);
INSERT INTO GOLD.DIM_PRODUCTOS (ID_PRODUCTO, NOMBRE_PRODUCTO, CATEGORIA, PRECIO_UNITARIO, LABORATORIO)
SELECT
     ID_PRODUCTO
    ,NOMBRE_PRODUCTO
    ,CATEGORIA
    ,PRECIO_UNITARIO
    ,LABORATORIO
FROM SILVER.PRODUCTOS;

-- TABLA DIM_VENDEDORES
CREATE OR REPLACE TABLE GOLD.DIM_VENDEDORES (
     ID_VENDEDOR            VARCHAR PRIMARY KEY
    ,NOMBRE_VENDEDOR        VARCHAR
    ,REGION_CO              VARCHAR
    ,FECHA_INGRESO          DATE
    ,TIPO_DE_CONTRATO       VARCHAR
);

INSERT INTO GOLD.DIM_VENDEDORES (ID_VENDEDOR, NOMBRE_VENDEDOR, REGION_CO, FECHA_INGRESO, TIPO_DE_CONTRATO)
SELECT
     ID_VENDEDOR
    ,NOMBRE_VENDEDOR
    ,REGION_CO
    ,FECHA_INGRESO
    ,TIPO_DE_CONTRATO
FROM SILVER.VENDEDORES;