-- ==== CREACIÓN DE GOLD LAYER ====

-- TABLA FACT_CUOTAS
CREATE OR REPLACE TABLE GOLD.FACT_CUOTAS (
    ID_CUOTA        VARCHAR PRIMARY KEY
    ,ID_VENDEDOR    VARCHAR REFERENCES GOLD.DIM_VENDEDORES(ID_VENDEDOR)
    ,PERIODO        DATE
    ,CUOTA_MENSUAL  NUMBER
); 

INSERT INTO GOLD.FACT_CUOTAS (ID_CUOTA, ID_VENDEDOR, PERIODO, CUOTA_MENSUAL)
SELECT
     ID_CUOTA
    ,ID_VENDEDOR
    ,PERIODO
    ,CUOTA_MENSUAL
FROM SILVER.CUOTA;

-- TABLA FACT_VENTAS
CREATE OR REPLACE TABLE GOLD.FACT_VENTAS (
    ID_VENTA        VARCHAR PRIMARY KEY,
    FECHA_VENTA     DATE,
    ID_PRODUCTO     VARCHAR REFERENCES GOLD.DIM_PRODUCTOS(ID_PRODUCTO),
    ID_CLIENTE      VARCHAR REFERENCES GOLD.DIM_CLIENTES(ID_CLIENTE),
    ID_VENDEDOR     VARCHAR REFERENCES GOLD.DIM_VENDEDORES(ID_VENDEDOR),
    ID_FECHA        INT     REFERENCES GOLD.DIM_TIEMPO(ID_FECHA),
    CANTIDAD        INT,
    PRECIO_UNITARIO NUMBER(18,2),
    TOTAL_VENTA     NUMBER(18,2)
);

INSERT INTO GOLD.FACT_VENTAS (ID_VENTA, FECHA_VENTA, ID_PRODUCTO, ID_CLIENTE, ID_VENDEDOR, ID_FECHA, CANTIDAD, PRECIO_UNITARIO, TOTAL_VENTA)
SELECT
     ID_VENTA
    ,FECHA_VENTA
    ,ID_PRODUCTO
    ,ID_CLIENTE
    ,ID_VENDEDOR
    ,B.ID_FECHA
    ,CANTIDAD
    ,PRECIO_UNITARIO
    ,TOTAL_VENTA
FROM SILVER.VENTAS AS A
INNER JOIN GOLD.DIM_TIEMPO AS B
    ON A.FECHA_VENTA = B.FECHA;